version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: nahua
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lenslocked
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracular
    ports:
      - 3333:8080